####################################
### Distem Experiment Param File ###
####################################
### Job Params
job:    "nancy/*"

### Deploy
env:    "wheezy-x64-nfs"

### Distem
vm:             4
vcore:          1
fsimg:          "file:///home/ejeanvoine/public/distem/distem-fs-wheezy.tar.gz"
nodes_file:     "/root/DISTEM_NODES"
net_file:       "/root/G5K_NET"
ssh_key:        'id_rsa'
ipfile:         "/tmp/distem_vnodes_ip"
cpu_algo:       "hogs"
# cpu_algo:       "gov"
distem_setup_file:      "/home/jemeras/public/distem/distem_tools/distem-setup.rb"
distem_setup_dest: 	"/root/distem-setup.rb"

### Stencil
CHARM_SOURCE: "/home/jemeras/public/distem/distem_experiments/charm-6.5.1/"
CHARM_HOME: '/root/charm-6.5.1'
CHARM_NODELIST_FILE: "nodelist"
arch: 'net-linux-x86_64'
compile_options: "-O3"

